# Generated by Django 4.2.4 on 2023-08-19 15:11

import backend.authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_remove_customuser_name_remove_customuser_picture_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to=backend.authentication.utils.pictureLocation,
            ),
        ),
    ]
